spring:
  batch:
    jdbc:
      initialize-schema: always
    job:
      names: ${job.name:NONE}
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database: h2
    show-sql: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
    password: sa123
