spring:
  batch:
    jdbc:
      initialize-schema: always
    job:
      names: ${job.name:NONE}
      enabled: false  #spring boot가 실행될때 해당 잡의 파라미터가 존대하더라도 해당 job을 실행시키지 않음
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database: h2
    show-sql: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
    password: sa123
